#!/usr/bin/perl
# $Id: find,v 1.12 2004/06/28 14:21:38 brondsem Exp $

# find   --	Find files
#
#	Arne Georg Gleditsch <argggh@ifi.uio.no>
#	Per Kristian Gjermshus <pergj@ifi.uio.no>
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

######################################################################

$CVSID = '$Id: find,v 1.12 2004/06/28 14:21:38 brondsem Exp $ ';

use lib do { $0 =~ m{(.*)/} ? "$1/lib" : "lib" };

use LXR::Common qw(:html);
use LXR::Config;

sub find {

print qq~
<p align=\"center\">
Search for files (by name) using regular expressions.
</p>
<H3>Quick tip:</H3>
<P>
The database that is searched has the form of the output of the
"find" command. 
</p><p>That is, each line is the absolute patch of a file
If you want to search for a specific file(s), you use
<ul>
<li> /el.po search for all occurences of file "el.po".
<li> .desktop search for all files ending with ".desktop".
</ul>
</p>
<p>
"\\" is for escaping characters (we escape
characters "/" and "." while "$" denotes the end of the string.
</p>
~;

    print ("<form method=\"get\" action=\"find\">\n");

    foreach ($config->allvariables) {
	if ($config->variable($_) ne $config->vardefault($_)) {
	    print("<input type=\"hidden\" name=\"",$_, "\" ",
		  "value=\"", $config->variable($_), "\">\n");
	}
    }			       
    
    print("<b>Find file: </b><input type=\"text\" name=\"string\" ",
	  "value=\"",$searchtext,"\" size=\"50\">\n",
	  "<input type=\"submit\" value=\"search\">\n",
	  "</form>\n");


    if ($searchtext ne "") {
    if ($config->swishdir and $config->swishindex) {
        unless (open(FILELLISTING,$config->swishdir."/$release.filenames")) {
            &warning("Version '$release' has not been indexed and is unavailable for searching<br>Could not open ".$config->swishdir."/$release.filenames.");
            return;
        }
    }
    if ($config->glimpsedir and $config->glimpseindex) {
        unless (open(FILELLISTING,$config->glimpsedir."/".$release."/.glimpse_filenames")) {
            &warning("Version '$release' has not been indexed and is unavailable for searching<br>Could not open ".$config->glimpsedir."/$release/.glimpse_filenames.");
            return;
        }
    }
	print("<hr>\n");
	$sourceroot = $config->sourceroot;
    my $hits = 0;
	while($file = <FILELLISTING>) {
	    $file =~ s/^$sourceroot//;
	    if($file =~ /$searchtext/) {
		print(&fileref("$file", "find-file", "/$file"),"<br>\n");
        $hits++;
	    }
	}
    print "<br>$hits files found.";
    }
}

httpinit;

$searchtext = $HTTP->{'param'}->{'string'};

&makeheader('find');
&find;
&makefooter('find');

httpclean;

