#!/usr/bin/perl
# $Id: find,v 1.14 2004/07/07 20:31:45 brondsem Exp $

# find   --	Find files
#
#	Arne Georg Gleditsch <argggh@ifi.uio.no>
#	Per Kristian Gjermshus <pergj@ifi.uio.no>
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

######################################################################

$CVSID = '$Id: find,v 1.14 2004/07/07 20:31:45 brondsem Exp $ ';

use lib do { $0 =~ m{(.*)/} ? "$1/lib" : "lib" };


use LXR::Common qw(:html);
use LXR::Config;

sub find {

    print ("<form method=\"get\" action=\"find\">\n");

    foreach ($config->allvariables) {
	if ($config->variable($_) ne $config->vardefault($_)) {
	    print("<input type=\"hidden\" name=\"",$_, "\" ",
		  "value=\"", $config->variable($_), "\">\n");
	}
    }			       
    
    print("<b>Find file: </b><input type=\"text\" name=\"string\" ",
	  "value=\"",$searchtext,"\" size=\"50\">\n",
	  "<input type=\"submit\" value=\"search\">\n",
	  "<br><input type=\"checkbox\" name=\"advanced\"", $advanced ? " checked" : "", " value=\"1\"/> Advanced (allow <a href=\"http://www.perldoc.com/perl5.8.4/pod/perlrequick.html\" target=\"_blank\">regex</a>)\n",
	  "&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"casesensitive\"", $casesensitive ? " checked" : "", " value=\"1\"/> Case-sensitive\n",
	  "</form>\n");


    if ($searchtext ne "") {
    if ($config->swishdir and $config->swishindex) {
        unless (open(FILELLISTING,$config->swishdir."/$release.filenames")) {
            &warning("Version '$release' has not been indexed and is unavailable for searching<br>Could not open ".$config->swishdir."/$release.filenames.");
            return;
        }
    }
    if ($config->glimpsedir and $config->glimpseindex) {
        unless (open(FILELLISTING,$config->glimpsedir."/".$release."/.glimpse_filenames")) {
            &warning("Version '$release' has not been indexed and is unavailable for searching<br>Could not open ".$config->glimpsedir."/$release/.glimpse_filenames.");
            return;
        }
    }
	print("<hr>\n");
	$sourceroot = $config->sourceroot;
	my $hits = 0;
	while($file = <FILELLISTING>) {
	    $file =~ s/^$sourceroot//;
	    if ($advanced) {
		if ($casesensitive) {
		    if ($file =~ /$searchtext/) {
			print(&fileref("$file", "find-file", "/$file"),"<br>\n");
			$hits++;
		    }
		} elsif ($file =~ /$searchtext/i) {
		    print(&fileref("$file", "find-file", "/$file"),"<br>\n");
		    $hits++;
		}
	    } else {
		if ($casesensitive) {
		    if (index($file,$searchtext) != -1) {
			print(&fileref("$file", "find-file", "/$file"),"<br>\n");
			$hits++;
		    }
		} elsif (index(lc($file),lc($searchtext)) != -1) {
		    print(&fileref("$file", "find-file", "/$file"),"<br>\n");
		    $hits++;
		}
	    }
	}
    print "<br>$hits files found.";
    }
}

httpinit;

$searchtext = $HTTP->{'param'}->{'string'};
$advanced = $HTTP->{'param'}->{'advanced'};
$casesensitive = $HTTP->{'param'}->{'casesensitive'};

&makeheader('find');
&find;
&makefooter('find');

httpclean;

